config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "home/login", :to=> 'home#login'
  get "home/toggle_notify", :to=> 'home#toggle_notify'
  get "del_notify/:idx", :to=> 'home#del_notify'
  get "add_notify", :to=> 'home#add_notify'
  get '/auth/:provider/callback', :to => 'sessions#callback'
  post '/auth/:provider/callback', :to => 'sessions#callback'
  get '/logout' => 'sessions#destroy', :as => :logout
  get 'modify_medicine_num', :to=> 'home#modify_medicine_num'
  get 'modify_medicine_desc', :to=> 'home#modify_medicine_desc'

  root 'home#index'

end

app/models/done_list.rb
class DoneList < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :done_list
  
  def self.create_with_omniauth(auth)
    #instruction(auth['info']['nickname'])
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.screen_name = auth['info']['nickname']
      user.name = auth['info']['name']
    end
  end
  
  private
  def self.instruction(screen_name)
    msg = "#{screen_name}さん、登録ありがとう！登録した時間に「お薬のんだ？」とつぶやきます。のんだら返信してね！"
    p msg
    #$tw_client.update(msg)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user

  private
  def current_user
     #現在のユーザーの情報を返す
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  protect_from_forgery

#ログイン状況を確認
  def login_required
    #セッション情報としてuser idがあれば、@current_userにユーザ情報をセットして返す
    if session[:user_id]
      begin
        @current_user = User.find(session[:user_id])
      rescue
        #セッションを保存しているidが見つからなかった場合の対処
        redirect_to home_login_path
      end
    #なければtopページにリダイレクト
    else
      redirect_to home_login_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < BaseController
  def index
    login_required
    
    unless @current_user.blank?
      #時刻情報の取得
      @time_info = []
      unless @current_user.json_time.blank?
        @time_info = @current_user.json_time
      end
      #薬の情報の取得
      @medicine_desc = @current_user.medicine_desc
      #薬の服用履歴を取得
      @history = DoneList.where(user_id: @current_user.id).where(is_reply: true).limit(10)
      #通知ステータスの情報
      if @current_user.notify == true
          @notify_status = "ON"
          @link_msg = "OFFにする"
      else
          @notify_status = "OFF"
          @link_msg = "ONにする"
      end
      #薬の残り日数の取得
      @medicine_num = 30 #デフォルト値
      @medicine_num = @current_user.medicine_num unless @current_user.medicine_num.blank?
    end
  end
  
  def login
  end
  
  def toggle_notify
    #通知のON/OFFを切り替える
    login_required
    
    if @current_user.notify == true
      @current_user.update_attribute(:notify, false)
      flash[:notice] = "通知をOFFにしました。"      
   else
     @current_user.update_attribute(:notify,  true)
     flash[:notice] = "通知をONにしました。通知を受け取るには@TasqelTonikaのアカウントのフォローもお願いします。"
    end
    redirect_to home_index_path
  end
  
    #日時の登録を確認
  def modify_medicine_num
    #薬の残りの日数の登録
    login_required #要ログインの項目    
    modify_num = params[:medicine_num]
    p modify_num
    #値の更新
    if @current_user.update({medicine_num: modify_num})
      flash[:notice] = "薬の残り日数を更新しました。"
    else
      flash[:alert] = "薬の残り日数を更新できませんでした。"
    end
    redirect_to home_index_path
    
  end

  def del_notify
    #指定された通知エントリを削除
    login_required
    
    idx = params[:idx].to_i
    unless @current_user.json_time.blank?
      j = @current_user.json_time
      j.delete_at(idx)
      logger.info("current json_data : #{j}")
       j = JSON.dump(j) if j.length > 1
      @current_user.update_attribute(:json_time, [])
      @current_user.update_attribute(:json_time, j) if j.length > 0
    end
    redirect_to home_index_path
  end
  
  def add_notify
    #通知エントリを追加
    login_required
    
    j = []
    unless @current_user.json_time.blank?
      j = @current_user.json_time
    end
    t = "#{params[:time]['(4i)']}:#{params[:time]['(5i)']}"
    j.push({desc: params[:desc], time: t})
    j = JSON.dump(j) if j.length > 1
    #j.sort! {|a,b| Time.parse(a["time"]) <=> Time.parse(b["time"])}
   @current_user.update_attribute(:json_time, j)
   
   redirect_to home_index_path   
  end
  
  def extend
    login_required
    
    if @current_user.blank?
      return
    end
        
     j = [{}]
    unless @current_user.json_time.blank?
      j = @current_user.json_time
    end
    
    id = params[:id].to_i
    if @current_user.id != id
      flash[:alert] = "異なるユーザに対するリクエストです。requested_id:#{id} / current_user.id:#{@current_user.id}"
    else  
      h = params[:hour]
      m = params[:min]
      idx = params[:idx].to_i
  
      t = "#{h}:#{m}"
      j[idx]["extend"] = true
      j[idx]["extended_time"] = t
      j = JSON.dump(j) if j.length > 1
     @current_user.update({json_time: j})
     flash[:notice] = "再通知のリクエストを受け付けました。再通知の時間：#{h}:#{m}"
   end
  end
  
  def modify_medicine_desc
    login_required
    modify_desc = params[:medicine_desc]
    p modify_desc
    
    if @current_user.update({medicine_desc: modify_desc})
      flash[:notice] = "薬の種類を変更しました。"
       @medicine_desc = modify_desc;
    else
      flash[:alert] = "薬の種類を更新できませんでした。"
    end
    redirect_to home_index_path
     
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def callback
    auth = request.env['omniauth.auth']
    user = User.find_by_provider_and_uid(auth['provider'], auth['uid']) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
#    session[:oauth_token] = auth['credentials']['token']
#    session[:oauth_token_secret] = auth['credentials']['secret']
    
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   #改行コードを<br>タグに変換するヘルパ
  def addBr(t)
    #既存の文字列のhtmlタグは無効化する（セキュリティのため）
    t = h(t)
    #テキストの改行コードをbrタグに変換
    return t.gsub(/(\r\n|\r|\n)/, "<br />")
  end
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def generate_desc(desc = nil)
    msg = "お薬を飲みました。"
    unless desc.blank?
      msg = "#{desc}のお薬を飲みました。"
    end
    return msg
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/extend.html.erb
   <div class="container">
      <div class="masthead">
      	<div class="nav nav-pills pull-right">
          	<%= link_to 'ログアウト', logout_path,  {class:  "btn btn-warning active btn-sm"} %>
        </div>
         <h3 class="muted">ようこそ<%= current_user.name %>さん</h3>
      </div>

      <!-- setting -->
      <div class="jumbotron">
      	<% if !flash[:notice].blank? %>
      		<div class="alert alert-success"><%= flash[:notice] %></div>
        <% elsif !flash[:alert].blank? %>
        		<div class="alert alert-warning"><%= flash[:alert] %></div>
        	<% end %>
　    </div>
       
      <!-- Site footer -->
      <footer class="footer">
        <p>&copy; Company 2014</p>
      </footer>
    </div> <!-- /container -->
</div>

app/views/home/index.html.erb
<div class="container">
      <div class="masthead">
      	<div class="nav nav-pills pull-right">
          	<%= link_to 'ログアウト', logout_path,  {class:  "btn btn-warning active btn-sm"} %>
        </div>
        <h3 class="muted">ようこそ<%= current_user.name %>さん</h3>
      </div>

      <!-- setting -->
      <div class="jumbotron">
      	<% if !flash[:notice].blank? %>
      		<div class="alert alert-success"><%= flash[:notice] %></div>
        <% elsif !flash[:alert].blank? %>
        	<div class="alert alert-warning"><%= flash[:alert] %></div>
        <% end %>
        <h3>通知の設定：<%= @notify_status %><%= link_to @link_msg,  home_toggle_notify_path,  {class:  "btn btn-primary active  btn-sm pull-right"}  %></h3>
        <br/>
        <h3>薬を飲む時間の登録</h3>
 
		<%= form_tag("/add_notify", method: "get", class: "form-inline") do %> 
　　　<table class="table">
        　<thead>
        　　<tr>
        　　　<th>#</th>
        　　　<th>タイミング</th>
        　　　<th>時間</th>
        　　　<th>編集</th>
        　　</tr>    
<!-- DBデータの表示エリア   -->
        　<tbody>
        	<!-- DBからのデータを繰り返し表示させる列です。 -->
        	<% @time_info.each_with_index do |t, idx| %>
        	<tr>
	     	　<td></td>
	     	　<td><%= t["desc"] %></td>
	     	　<td><%= t["time"] %></td>
	     	　<td>
	     		<a href="/del_notify/<%= idx %>" class="btn btn-default btn-lg">
				  <span class="glyphicon glyphicon-trash"></span> 削除
				</a>
			　</td>
		　</tr>
         <% end %>

            <!-- 登録用のフォームの列です。 -->
            <tr>          
	     	　<td>
	     	</td>
	     	　<td>
	     		<%= text_field_tag 'desc', @desc, placeholder: "例）昼", class: "exampleInputEmail2 form-control" %>
	     	　</td>
	     	　<td id="time_area">
	     		<%= time_select(:time, @time, { :minute_step => 5, :default => { :hour => 12, :minute => 0} }, { :class => 'exampleInputEmail2 form-control' }) %>
	     	　</td>
	     	　<td>
	     	    <!--<%= submit_tag '+ 追加' , class:"btn btn-default btn-lg" %>-->
	     	    <input class="btn btn-default btn-lg" name="commit" type="submit" value="+ 追加" />
	     	　</td>
         　　</tr>
         </tbody>
       </table>
       <% end %>
       <!-- DBからの表示の終了 --> 
       <br/>
       <h3>薬の種類</h3>
        <table class="table">
        	<tr>
       		  <%= form_tag("/modify_medicine_desc", method: "get", class: "form-inline") do %>
       		  <td>
       			<%= text_area_tag 'medicine_desc', @medicine_desc, placeholder: @medicine_desc, class: "exampleInputEmail6 form-control resizable", id:"desc_text" %>
       		  </td>
       	  　　<td>
	           <input class="exampleInputEmail6 btn btn-default btn-lg" id="desc_input" name="commit" type="submit" value="変更" />
	     	 </td>
	     	  <% end %>
       		</tr>
       </table>
       <h3 class="pull-left">薬を取りに行くまでの日数</h3>
       <%= form_tag("/modify_medicine_num", method: "get", class:"form-inline") do %>       
　      　<table class="table">
         	<tr>
	     　 <td></td>
	     　 <td class="text-right"><h4>残り日数</h4></td>
	     　 <td>	     	
		   	  <%= text_field_tag 'medicine_num', @medicine_num, placeholder: @medicine_num, class: "exampleInputEmail2 form-control text-right pull-right" %>
              </td>
            <td><h4>日</h4></td>
	     　<td>
	     	<%= submit_tag '設定' , class:"btn btn-default btn-lg" %>
		 　</td>
         </tr> 
         </table>
         <% end %>
         <h3 class="pull-left">お薬服用の履歴</h3> 
         <table class="table">
         		<% if @history.blank? %>
	         		<tr>
	         			<td>まだ履歴はありません。</td>
	         			<td></td>
	         		</tr>
         		<% else %>
	         		<% @history.each do |h| %>
	         		<tr>
	         			<td><h4><%= h.reply_time.strftime("%Y年%m月%d日 %H時%M分ごろ") %> に<%= generate_desc(h.desc) %></h4></td>
	         		</tr>
	         		<% end %>
         		<% end %>
         </table>	
　    </div>
       
      <!-- Site footer -->
      <footer class="footer">
        <p>&copy; Team Tonika 2014</p>
      </footer>
    </div> <!-- /container -->
</div>

app/views/home/login.html.erb
<div id="containerBox">
	<div class="container">
	  <div id="inputArea">
		<%= image_tag 'login_logo.png', alt:'bg', id:'login_logo' %>
	  <div id="data_inputArea">
	  	<div id="quelText">
	     <h1 class="text-center"><span class="tasu">＋</span>Quel</h1><br/>
	     <p class="text-center"><span class="tasu">＋</span>Quelはお薬リマインダーアプリです。<br/>カプくんとタブくんの二人が<br/>あなたに薬の時間をおしらせします。</p><br/><br/>
	     <p class="text-center">Twitterアカウントでログイン<br/></p><br/>
	    </div>
	    <div class="row placeholders" id="characters">
	    	<div class="col-md-4 col-sm-4 col-xs-2 placeholder">
	    	  <%= image_tag 'kapu.png', alt:'kapukun', class:'img-responsive hidden-xs' %>
              <h4 id="kapu" class="hidden-xs">カプくん</h4>
            </div>
            <div class="col-xs-8 col-sm-4 ">
            	<%= link_to 'Log in', '/auth/twitter?x_auth_access_type=read', {class:"btn btn-primary btn-lg btn-block", id:"loginBtn"}%>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-2 placeholder">
              <%= image_tag 'tabu.png', alt:'tabukun', class:'img-responsive hidden-xs' %>
              <h4 id="tabu" class="hidden-xs">タブくん</h4>
            </div>
		</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasquel</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield :header %>
  <%= favicon_link_tag '/favicon.ico' %>
  <!-- BootStrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</head>
<body>
<%= yield %>
</body>
</html>